services:
  task-server:
    image: asia-northeast2-docker.pkg.dev/todo-project-471103/todo-poc-repo/todo-task:v0.1.0-rc2
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - JWT_SECRET=secret-key-for-testing
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
        driver: local
