services:
  server:
    build:
      context: ./server
      target: dev
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/app
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development-dependencies-env
    command: pnpm run dev --host 0.0.0.0
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    working_dir: /app
    depends_on:
      - server

volumes:
    postgres_data:
        driver: local
